services:
  postgres:
    image: "postgres:16-alpine"
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
    networks:
      - connecthub-network
  connecthub-service:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: connecthub-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_URL: ${DB_URL}
      AUTH_SERVICE_URL: http://user-service-app:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - connecthub-network

  connecthub-frontend:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: connecthub-frontend
    ports:
      - "5173:80"
    env_file:
      - .env
    environment:
      VITE_API_BASE_URL: http://connecthub-service:8080
    depends_on:
      - connecthub-service
    networks:
      - connecthub-network

volumes:
  postgres_data:

networks:
  connecthub-network:
    external: true
