FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci
COPY . .

ARG VITE_API_BASE_URL=
ARG VITE_AUTH_URL=http://localhost:3000
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_AUTH_URL=$VITE_AUTH_URL
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]