spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://postgres:5432/user_service_db
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.access-token-expiry-minutes=30
jwt.refresh-token-expiry-days=7
jwt.issuer-uri=http://localhost:8081
