spring.application.name=connecthub-service
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=false

server.servlet.session.cookie.same-site=none

spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

auth.service.jwks-uri=${AUTH_SERVICE_URL:http://auth-service:8080}/.well-known/jwks.json

launchpad.service.url=${LAUNCHPAD_SERVICE_URL:http://launchpad-service:8080}
