name: connecthub-frontend

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-node-ci.yml
    with:
      service-path: connecthub/frontend
      image-name: connecthub-frontend
