name: connecthub-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-java-ci.yml
    with:
      service-path: connecthub/backend
      image-name: connecthub-backend
      use-postgres: true
