name: launchpad-backend

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-java-ci.yml
    with:
      service-path: launchpad/backend
      image-name: launchpad-backend
      oauth2-issuer-uri: http://localhost:8081
