name: launchpad-frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-node-ci.yml
    with:
      service-path: launchpad/frontend
      image-name: launchpad-frontend
      run-typecheck: true
