name: launchpad-frontend

on:
  push:
    branches: [main]
    paths:
      - launchpad/frontend/**
      - .github/workflows/launchpad-frontend.yml
      - .github/workflows/_reusable-node-ci.yml
  pull_request:
    branches: [main]
    paths:
      - launchpad/frontend/**
      - .github/workflows/launchpad-frontend.yml
      - .github/workflows/_reusable-node-ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-node-ci.yml
    with:
      service-path: launchpad/frontend
      image-name: hatchloom-frontend
      run-typecheck: true
