name: launchpad-backend

on:
  push:
    branches: [main]
    paths:
      - launchpad/backend/**
      - launchpad/docker-compose.yaml
      - .github/workflows/launchpad-backend.yml
      - .github/workflows/_reusable-java-ci.yml
  pull_request:
    branches: [main]
    paths:
      - launchpad/backend/**
      - launchpad/docker-compose.yaml
      - .github/workflows/launchpad-backend.yml
      - .github/workflows/_reusable-java-ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-java-ci.yml
    with:
      service-path: launchpad/backend
      image-name: hatchloom-launchpad
      use-postgres: true
      oauth2-issuer-uri: http://localhost:8081
