name: user-service-backend

on:
  push:
    branches: [main]
    paths:
      - user-service/src/**
      - user-service/pom.xml
      - user-service/mvnw
      - user-service/Dockerfile
      - .github/workflows/user-service-backend.yml
      - .github/workflows/_reusable-java-ci.yml
  pull_request:
    branches: [main]
    paths:
      - user-service/src/**
      - user-service/pom.xml
      - user-service/mvnw
      - user-service/Dockerfile
      - .github/workflows/user-service-backend.yml
      - .github/workflows/_reusable-java-ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-java-ci.yml
    with:
      service-path: user-service
      image-name: user-service
      jwt-secret: test-secret-key-for-ci-cd-pipeline-at-least-256-bits
