name: user-service-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_reusable-java-ci.yml
    with:
      service-path: user-service
      image-name: user-service-backend
      jwt-secret: test-secret-key-for-ci-cd-pipeline-at-least-256-bits
